export const vietnamese = {
    homePage: {
        header: {
            login: 'Đăng Nhập',
            register: 'Đăng Ký',
            hello: 'Xin chào',
            loginSuccess: 'Đăng nhập thành công',
            logOut: 'Đăng Xuất',
            changePassword: 'Đổi Mật Khẩu',
            currentPassword: 'Mật khẩu hiện tại',
            newPassword: 'Mật khẩu mới',
            confirmNewPassword: 'Nhập lại mật khẩu mới',
            successPassword: 'Thay đổi mật khẩu thành công',
            cancelChange: 'Hủy thay đổi',
            saveChange: 'Lưu thay đổi',
            modifyInfor: 'Thay Đổi Thông Tin Của Bạn',
            specialist: 'Chuyên Khoa',
            findDoctor: 'tìm bác sĩ theo chuyên khoa',
            facility: 'Cơ Sở Y Tế',
            selectHospital: 'Chọn bệnh viện phòng khám',
            doctor: 'Bác Sĩ',
            selectDoctor: 'Chọn bác sĩ giỏi',
            packageCheck: 'Gói Khám',
            checkHeath: 'Khám sức khỏe tổng quát',
            assist: 'Hỗ Trợ',
            medical: 'Nên tảng y tế',
            heathCare: 'Chăm sóc sức khỏe toàn diện',
            findHospital: 'Tìm bệnh viện',
            checkSpecialist: 'Khám chuyên khoa',
            checkRemote: 'Khám từ xa',
            checkGeneral: 'Khám tổng quát',
            testMedical: 'Xét nghiệm y học',
            metalHealth: 'Sức khỏe tinh thần',
            checkDetal: 'Khám nha khoa',
            packageSurgery: 'Gói phẫu thuật',
            medicalProduct: 'Sản phẩm y tế'
        },
        content: {
            specialist: 'Chuyên khoa phổ biến',
            moreDetail: 'Xem thêm',
            facility: 'Cơ sở y tế nổi bật',
            search: 'Tìm kiếm',
            famousDoctor: 'Bác sĩ nổi bật tuần qua',
            handbook: 'Cẩm nang',
            allHandbook: 'Tất cả bài viết'
        },
        footer: {
            downloadBooking: 'Tải ứng dụng BookingCare',
            bookFaster: 'Đặt khám nhanh hơn',
            getAnnouce: 'Nhận thông báo từ hệ thống',
            getInstruction: 'Nhận hướng dẫn đi khám chi tiết',
            openLink: 'Hoặc mở liên kết :'
        }
    }, formLog: {
        login: 'Đăng Nhập',
        register: 'Đăng Ký',
        useName: 'Tên đăng nhập',
        password: 'Mật khẩu',
        forgotPassword: 'Quên mật khẩu ?',
        or: 'hoặc',
        createUser: 'Tạo tài khoản mới',
        fullname: 'Tên đầy đủ',
        phoneNumber: 'Số điện thoại',
        email: 'Email',
        gender: 'Giới tính',
        position: 'Chức danh',
        department: 'Vai trò',
        rePassword: 'Nhập lại mật khẩu',
        avatar: 'Ảnh đại diện',
        createSucess: 'Tạo tài khoản thành công',
        editSuccess: 'Sửa đổi thông tin của bạn thành công',
        goBack: 'Quay Lại',
        edit: 'Sửa Đổi',
        createMessage: 'Chúc mừng ! Bạn đã tạo thành khoản thành công tại hệ thống của tôi:',
        registerAnother: 'Đăng ký tài khoản khác',
        toLogin: 'Tới cửa sổ đăng nhập',
        owner: 'Ducquyetns2',
        errorMessage: {
            isRequire: 'Vui lòng nhập trường này',
            maxLength: 'Nhập số ký tự tối đa là: ',
            minLength: 'Nhập số ký tự tối thiểu là: ',
            isNumber: 'Vui lòng nhập đúng định dạng số',
            isEmail: 'Vui lòng nhập đúng định dạng email',
            isAccents: 'Vui lòng không nhập ký tự có dấu',
            isFile: 'Vui lòng chọn đúng định dạng file',
            isConfirm: 'Mật khẩu nhập lại không chính xác',
            existUsename: 'Tên đăng nhập đã tồn tại. Vui lòng thử tên đăng nhập khác',
            wrongUser: 'Tên đăng nhập hoặc mật khẩu không chính xác !',
            wrongPassword: 'Mật khẩu không chính xác',
            isSimilar: 'Mật khẩu mới phải khác mật khẩu hiện tại'
        }
    }, admin: {
        listAccount: 'Danh Sách Tài Khoản',
        fullname: 'Tên đầy đủ',
        phoneNumber: 'Số điện thoại',
        email: 'Email',
        gender: 'Giới tính',
        useName: 'Tên đăng nhập',
        password: 'Mật khẩu',
        avatar: 'Ảnh đại diện',
        position: 'Chức Danh',
        department: 'Vai Trò',
        createUser: 'Tạo tài khoản mới',
        createdAt: 'Ngày Tạo',
        updatedAt: 'Ngày cập nhật',
        no: 'Không',
        action: 'Hành Động',
        delete: 'Xóa',
        edit: 'Sửa',
        deleteTitle: 'Bạn có chắc chắn muốn xóa tài khoản này không ?',
        deleteConfirm: 'Hành động này của bạn sẽ xóa vĩnh viễn tài khoản khỏi hệ thống và không thể khôi phục lại được !',
        close: 'Đóng',
        deleteSucess: 'Xóa tài khoản thành công',
        deleteFail: 'Xóa tài khoản thất bại !'
    }
}
export const english = {
    homePage: {
        header: {
            login: 'Log In',
            register: 'Register',
            hello: 'Hello',
            loginSuccess: 'Logged in successfully',
            logOut: 'Log Out',
            changePassword: 'Change Password',
            currentPassword: 'Current password',
            newPassword: 'New password',
            confirmNewPassword: 'Re-enter new password',
            successPassword: 'Change password successfully',
            cancelChange: 'Cancel change',
            saveChange: 'Save change',
            modifyInfor: 'Modify Your InforMation',
            specialist: 'Specialist',
            findDoctor: 'Find doctors by specialty',
            facility: 'Health Facilities',
            selectHospital: 'Choose hospital clinic',
            doctor: 'Doctor',
            selectDoctor: 'Choose professional doctors',
            packageCheck: 'Heath Package',
            checkHeath: 'Comprehensive health check',
            assist: 'Assistance',
            medical: 'Medical background',
            heathCare: 'Comprehensive health care',
            findHospital: 'Find hospitals',
            checkSpecialist: 'Specialist check',
            checkRemote: 'Remote check',
            checkGeneral: 'General check',
            testMedical: 'Medical test',
            metalHealth: 'Metal health',
            checkDetal: 'Detal check',
            packageSurgery: 'Surgery package',
            medicalProduct: 'Medical product'
        },
        content: {
            specialist: 'Popular specialist',
            moreDetail: 'More detail ',
            facility: 'Outstanding medical facility',
            search: 'Search',
            famousDoctor: 'Famous doctor of last week',
            handbook: 'Handbook',
            allHandbook: 'All posts'
        },
        footer: {
            downloadBooking: 'Download BookingCare',
            bookFaster: 'Book an appointment faster',
            getAnnouce: 'Recieve notifications from the system',
            getInstruction: 'Recieve detailed instructions',
            openLink: 'Or open the link'
        }
    }, formLog: {
        login: 'Log In',
        register: 'Register',
        useName: 'useName',
        password: 'Password',
        forgotPassword: 'Forgot password ?',
        position: 'Position',
        department: 'Department',
        or: 'Or',
        createUser: 'Create a new Acount',
        fullname: 'FullName',
        gender: 'Gender',
        phoneNumber: 'Phone Number',
        email: 'Email',
        rePassword: 'Re-Enter Password',
        avatar: 'Avatar',
        createSucess: 'Create Account Successfully',
        editSuccess: 'Change your information sucessfully',
        createMessage: 'Congratulations! You have successfully created an account in my system',
        goBack: 'Go Back',
        edit: 'Change',
        registerAnother: 'Register another account',
        toLogin: 'To the login window',
        owner: 'Ducquyetns2',
        errorMessage: {
            isRequire: 'please enter this field',
            maxLength: 'Enter the maximum number of characters: ',
            minLength: 'Enter the minimum number of characters: ',
            isNumber: 'Please enter the correct number format',
            isEmail: 'Please enter the correct email format',
            isAccents: 'Please do not enter accented characters',
            isFile: 'Please select the correct file format',
            isConfirm: 'Re-entered password is incorrect',
            existUsename: 'useName available. Please try another useName',
            wrongUser: 'useName or Password is incorrect !',
            wrongPassword: 'Password is wrong',
            isSimilar: 'New password must be different from current password'
        }
    }, admin: {
        listAccount: 'List of Account',
        fullname: 'FullName',
        phoneNumber: 'PhoneNumber',
        email: 'Email',
        gender: 'Gender',
        useName: 'UseName',
        password: 'Password',
        avatar: 'Avatar',
        position: 'Position',
        no: 'No',
        department: 'Department',
        createUser: 'Create a new Acount',
        createdAt: 'CreatedAt',
        updatedAt: 'UpdatedAt',
        action: 'Action',
        delete: 'Delete',
        edit: 'Edit',
        deleteTitle: 'Are you sure you want to delete this account ?',
        deleteConfirm: 'This action will permanently delete your account from my system and cannot be restored !',
        close: 'Close',
        deleteSucess: 'Delete account successfully',
        deleteFail: 'Delete account failure !'
    }
}