export const vietnamese = {
    homePage: {
        header: {
            login: 'Đăng Nhập',
            register: 'Đăng Ký',
            hello: 'Xin chào',
            loginSuccess: 'Đăng nhập thành công',
            logOut: 'Đăng Xuất',
            changePassword: 'Đổi Mật Khẩu',
            currentPassword: 'Mật khẩu hiện tại',
            newPassword: 'Mật khẩu mới',
            confirmNewPassword: 'Nhập lại mật khẩu mới',
            successPassword: 'Thay đổi mật khẩu thành công',
            cancelChange: 'Hủy thay đổi',
            saveChange: 'Lưu thay đổi',
            modifyInfor: 'Thay Đổi Thông Tin Của Bạn',
            specialty: 'Chuyên Khoa',
            findDoctor: 'tìm bác sĩ theo chuyên khoa',
            facility: 'Cơ Sở Y Tế',
            selectHospital: 'Chọn bệnh viện phòng khám',
            doctor: 'Bác Sĩ',
            chooseDoctor: 'Chọn bác sĩ giỏi',
            packageCheck: 'Gói Khám',
            checkHeath: 'Khám sức khỏe tổng quát',
            assist: 'Hỗ Trợ',
            medical: 'Nên tảng y tế',
            heathCare: 'Chăm sóc sức khỏe toàn diện',
            findHospital: 'Tìm bệnh viện',
            checkSpecialist: 'Khám chuyên khoa',
            checkRemote: 'Khám từ xa',
            checkGeneral: 'Khám tổng quát',
            testMedical: 'Xét nghiệm y học',
            metalHealth: 'Sức khỏe tinh thần',
            checkDetal: 'Khám nha khoa',
            packageSurgery: 'Gói phẫu thuật',
            medicalProduct: 'Sản phẩm y tế'
        },
        content: {
            specialty: 'Chuyên khoa phổ biến',
            moreDetail: 'Xem thêm',
            facility: 'Cơ sở y tế nổi bật',
            search: 'Tìm kiếm',
            famousDoctor: 'Bác sĩ nổi bật tuần qua',
            handbook: 'Cẩm nang',
            allHandbook: 'Tất cả bài viết'
        },
        footer: {
            downloadBooking: 'Tải ứng dụng BookingCare',
            bookFaster: 'Đặt khám nhanh hơn',
            getAnnouce: 'Nhận thông báo từ hệ thống',
            getInstruction: 'Nhận hướng dẫn đi khám chi tiết',
            openLink: 'Hoặc mở liên kết :'
        }
    }, formLog: {
        login: 'Đăng Nhập',
        register: 'Đăng Ký',
        useName: 'Tên đăng nhập',
        password: 'Mật khẩu',
        forgotPassword: 'Quên mật khẩu ?',
        or: 'hoặc',
        createUser: 'Tạo tài khoản mới',
        fullname: 'Tên đầy đủ',
        phoneNumber: 'Số điện thoại',
        email: 'Email',
        gender: 'Giới tính',
        position: 'Chức danh',
        department: 'Vai trò',
        rePassword: 'Nhập lại mật khẩu',
        avatar: 'Ảnh đại diện',
        createSucess: 'Tạo tài khoản thành công',
        editSuccess: 'Sửa đổi thông tin của bạn thành công',
        goBack: 'Quay Lại',
        edit: 'Sửa Đổi',
        createMessage: 'Chúc mừng ! Bạn đã tạo thành khoản thành công tại hệ thống của tôi:',
        registerAnother: 'Đăng ký tài khoản khác',
        toLogin: 'Tới cửa sổ đăng nhập',
        owner: 'Ducquyetns2',
        errorMessage: {
            isChoose: 'Vui lòng chọn trường này',
            isRequire: 'Vui lòng nhập trường này',
            maxLength: 'Nhập số ký tự tối đa là: ',
            minLength: 'Nhập số ký tự tối thiểu là: ',
            isNumber: 'Vui lòng nhập đúng định dạng số',
            isEmail: 'Vui lòng nhập đúng định dạng email',
            isAccents: 'Vui lòng không nhập ký tự có dấu',
            isFile: 'Vui lòng chọn đúng định dạng file',
            isConfirm: 'Mật khẩu nhập lại không chính xác',
            existUsename: 'Tên đăng nhập đã tồn tại. Vui lòng thử tên đăng nhập khác',
            wrongUser: 'Tên đăng nhập hoặc mật khẩu không chính xác !',
            wrongDetailUser: 'Tên đăng nhập, mật khẩu hoặc vai trò bạn chọn không chính xác !',
            wrongPassword: 'Mật khẩu không chính xác',
            isSimilar: 'Mật khẩu mới phải khác mật khẩu hiện tại'
        }
    }, admin: {
        listAccount: 'Danh Sách Tài Khoản',
        fullname: 'Tên đầy đủ',
        phoneNumber: 'Số điện thoại',
        email: 'Email',
        gender: 'Giới tính',
        useName: 'Tên đăng nhập',
        password: 'Mật khẩu',
        avatar: 'Ảnh đại diện',
        position: 'Chức Danh',
        department: 'Vai Trò',
        createUser: 'Tạo tài khoản mới',
        createdAt: 'Ngày Tạo',
        updatedAt: 'Ngày cập nhật',
        no: 'Không',
        action: 'Hành Động',
        delete: 'Xóa',
        edit: 'Sửa',
        deleteTitle: 'Bạn có chắc chắn muốn xóa tài khoản này không ?',
        deleteConfirm: 'Hành động này của bạn sẽ xóa vĩnh viễn tài khoản khỏi hệ thống và không thể khôi phục lại được !',
        close: 'Đóng',
        deleteSucess: 'Xóa tài khoản thành công',
        deleteFail: 'Xóa tài khoản thất bại !',
        manage: 'Quản lý',
        manageDoctor: 'Quản lý bác sĩ',
        manageSchedule: 'Quản lý lịch khám',
        manageHospital: 'Quản lý bệnh viện',
        manageHandbook: 'Quản lý bài viết',
        manageUser: 'Quản lý người dùng',
        manageSpecialty: 'Quản lý chuyên khoa',
        doctor: 'Bác sĩ',
        user: 'Người dùng',
        handbook: 'Bài viết',
        hospital: 'Bệnh viện',
        specialty: 'Chuyên khoa',
        schedule: 'Lịch khám',
        goBack: 'Quay lại',
        content: 'Nội dung',
        doctorInfor: {
            moreInfor: 'Thêm thông tin bác sĩ',
            chooseDoctor: 'Chọn bác sĩ',
            introVi: 'Thông tin giới thiệu (Tiếng Việt)',
            introEn: 'Thông tin giới thiệu (Tiếng Anh)',
            medicalPrice: 'Giá khám bệnh',
            paymentMethod: 'Phương thức thanh toán',
            province: 'Tỉnh thành',
            specialty: 'Chuyên Khoa',
            hospital: 'Bệnh viện',
            clinicAddressVi: 'Địa chỉ phòng khám (Tiếng Việt)',
            clinicAddressEn: 'Địa chỉ phòng khám (Tiếng Anh)',
            createSuccess: 'Tạo thông tin bác sĩ thành công',
            editSuccess: 'Sửa đổi thông tin bác sĩ thành công',
            change: 'Thay đổi',
            save: 'Lưu thay đổi',
            cancel: 'Hủy bỏ'
        },
        scheduleInfor: {
            examinationPlan: "Quản lý kế hoạch khám bệnh của bác sĩ",
            change: 'Thay đổi',
            save: 'Lưu thay đổi',
            chooseDoctor: 'Chọn bác sĩ',
            chooseDate: 'Chọn ngày',
            chooseMedicalDate: 'Chọn ngày khám bệnh',
            created: 'đã tạo',
            chooseTime: 'Chọn thời gian khám',
            createSuccess: 'Tạo lịch khám cho bác sĩ thành công',
            noCreated: 'Không có lịch khám nào được tạo',
            cancel: 'Hủy bỏ'
        },
        specialtyInfor: {
            moreInfor: 'Thêm thông tin chuyên khoa',
            avatar: 'Ảnh đại diện',
            chooseSpecialty: 'Chọn chuyên khoa',
            introVi: 'Thông tin giới thiệu (Tiếng Việt)',
            introEn: 'Thông tin giới thiệu (Tiếng Anh)',
            specialty: 'Chuyên Khoa',
            createSuccess: 'Tạo thông tin chuyên khoa thành công',
            editSuccess: 'Sửa đổi thông tin chuyên khoa thành công',
            change: 'Thay đổi',
            save: 'Lưu thay đổi',
            cancel: 'Hủy bỏ'
        },
        hospitalInfor: {
            moreInfor: 'Thêm thông tin bệnh viện',
            avatar: 'Ảnh đại diện',
            chooseHospital: 'Chọn bệnh viện',
            introVi: 'Thông tin giới thiệu (Tiếng Việt)',
            introEn: 'Thông tin giới thiệu (Tiếng Anh)',
            hospital: 'Bệnh viện',
            createSuccess: 'Tạo thông tin bệnh viện thành công',
            editSuccess: 'Sửa đổi thông tin bệnh viện thành công',
            change: 'Thay đổi',
            save: 'Lưu thay đổi',
            cancel: 'Hủy bỏ'
        },
        handbookInfor: {
            moreInfor: 'Tạo bài viết',
            image: 'Ảnh bài viết',
            createNew: 'Tạo mới bài viết',
            editHandbook: 'Sửa đổi bài viết đã tạo',
            chooseHandbook: 'Chọn danh sách bài viết đã tạo',
            contentVi: 'Nội dung (Tiếng Việt)',
            titleVi: 'Tiêu đề (Tiếng Việt)',
            contentEn: 'Nội dung (Tiếng Anh)',
            titleEn: 'Tiêu đề (Tiếng Anh)',
            handbook: 'Bài viết',
            createSuccess: 'Tạo bài viết thành công',
            editSuccess: 'Sửa đổi bài viết thành công',
            change: 'Thay đổi',
            save: 'Lưu thay đổi',
            create: 'Tạo mới',
            cancel: 'Hủy bỏ'
        }
    }, detailDoctor: {
        schedule: 'Lịch khám',
        address: 'Địa chỉ khám',
        price: 'Giá khám',
        specialty: 'Chuyên khoa: ',
        description: 'Mô tả: ',
        priority: 'Được ưu tiên khám trước khi đặt khám qua BookingCare',
        showDetail: 'Xem chi tiết',
        hiddenDetail: 'Ẩn bảng giá',
        paymentMethod: 'Người bệnh có thể thanh toán chi phí bằng hình thức : ',
        examinationBooking: 'Đặt lịch khám',
        examinationDate: 'Ngày khám: ',
        examinationTime: 'Thời gian',
        examinationReason: 'Lý do khám',
        book: 'Đặt',
        cancel: 'Hủy',
        bookingSuccess: 'Bạn đã đặt lịch khám thành công',
        exceedBooking: 'Bạn đã đặt quá số lượng lịch hẹn (Tối đa: 10)',
        dulicateBooking: 'lịch khám tại thời gian này đã được đặt trước đó'
    }
}
export const english = {
    homePage: {
        header: {
            login: 'Log In',
            register: 'Register',
            hello: 'Hello',
            loginSuccess: 'Logged in successfully',
            logOut: 'Log Out',
            changePassword: 'Change Password',
            currentPassword: 'Current password',
            newPassword: 'New password',
            confirmNewPassword: 'Re-enter new password',
            successPassword: 'Change password successfully',
            cancelChange: 'Cancel change',
            saveChange: 'Save change',
            modifyInfor: 'Modify Your InforMation',
            specialty: 'Specialist',
            findDoctor: 'Find doctors by specialty',
            facility: 'Health Facilities',
            selectHospital: 'Choose hospital',
            doctor: 'Doctor',
            chooseDoctor: 'Choose professional doctors',
            packageCheck: 'Heath Package',
            checkHeath: 'Comprehensive health check',
            assist: 'Assistance',
            medical: 'Medical background',
            heathCare: 'Comprehensive health care',
            findHospital: 'Find hospitals',
            checkSpecialist: 'Specialist check',
            checkRemote: 'Remote check',
            checkGeneral: 'General check',
            testMedical: 'Medical test',
            metalHealth: 'Metal health',
            checkDetal: 'Detal check',
            packageSurgery: 'Surgery package',
            medicalProduct: 'Medical product'
        },
        content: {
            specialty: 'Popular specialty',
            moreDetail: 'More detail ',
            facility: 'Outstanding medical facility',
            search: 'Search',
            famousDoctor: 'Famous doctor of last week',
            handbook: 'Handbook',
            allHandbook: 'All posts'
        },
        footer: {
            downloadBooking: 'Download BookingCare',
            bookFaster: 'Book an appointment faster',
            getAnnouce: 'Recieve notifications from the system',
            getInstruction: 'Recieve detailed instructions',
            openLink: 'Or open the link'
        }
    }, formLog: {
        login: 'Log In',
        register: 'Register',
        useName: 'useName',
        password: 'Password',
        forgotPassword: 'Forgot password ?',
        position: 'Position',
        department: 'Department',
        or: 'Or',
        createUser: 'Create a new Acount',
        fullname: 'FullName',
        gender: 'Gender',
        phoneNumber: 'Phone Number',
        email: 'Email',
        rePassword: 'Re-Enter Password',
        avatar: 'Avatar',
        createSucess: 'Create Account Successfully',
        editSuccess: 'Change your information sucessfully',
        createMessage: 'Congratulations! You have successfully created an account in my system',
        goBack: 'Go Back',
        edit: 'Change',
        registerAnother: 'Register another account',
        toLogin: 'To the login window',
        owner: 'Ducquyetns2',
        errorMessage: {
            isChoose: 'please choose this field',
            isRequire: 'please enter this field',
            maxLength: 'Enter the maximum number of characters: ',
            minLength: 'Enter the minimum number of characters: ',
            isNumber: 'Please enter the correct number format',
            isEmail: 'Please enter the correct email format',
            isAccents: 'Please do not enter accented characters',
            isFile: 'Please select the correct file format',
            isConfirm: 'Re-entered password is incorrect',
            existUsename: 'UseName available. Please try another useName',
            wrongUser: 'UseName or Password is incorrect !',
            wrongDetailUser: 'UseName, Password or Department you selected is incorrect !',
            wrongPassword: 'Password is wrong',
            isSimilar: 'New password must be different from current password'
        }
    }, admin: {
        listAccount: 'List of Account',
        fullname: 'FullName',
        phoneNumber: 'PhoneNumber',
        email: 'Email',
        gender: 'Gender',
        useName: 'UseName',
        password: 'Password',
        avatar: 'Avatar',
        position: 'Position',
        no: 'No',
        department: 'Department',
        createUser: 'Create a new Acount',
        createdAt: 'CreatedAt',
        updatedAt: 'UpdatedAt',
        action: 'Action',
        delete: 'Delete',
        edit: 'Edit',
        deleteTitle: 'Are you sure you want to delete this account ?',
        deleteConfirm: 'This action will permanently delete your account from my system and cannot be restored !',
        close: 'Close',
        deleteSucess: 'Delete account successfully',
        deleteFail: 'Delete account failure !',
        manage: 'Manage',
        manageDoctor: 'Manage doctor',
        manageSchedule: 'Manage schedule',
        manageHospital: 'Manage hospital',
        manageHandbook: 'Manage handbook',
        manageSpecialty: 'Manage specialty',
        doctor: 'Doctor',
        user: 'User',
        handbook: 'Handbook',
        hospital: 'Hospital',
        schedule: 'Schedule',
        specialty: 'Specialty',
        goBack: 'Go back',
        manageUser: 'Manage user',
        content: 'Content',
        doctorInfor: {
            moreInfor: 'More doctor information',
            chooseDoctor: 'Choose doctor',
            introVi: 'Introductory information (Vietnamese)',
            introEn: 'Introductory information (English)',
            medicalPrice: 'Medical price',
            paymentMethod: 'Payment method',
            province: 'Province',
            specialty: 'Specialty',
            hospital: 'Hospital name',
            clinicAddressVi: 'Clinic address (Vietnamese)',
            clinicAddressEn: 'Clinic address (English)',
            createSuccess: 'Create doctor information successfully',
            editSuccess: 'Edit doctor information successfully',
            save: 'Save changes',
            change: 'Change',
            cancel: 'Cancel'
        },
        scheduleInfor: {
            examinationPlan: "Manage the doctor's examination plan",
            save: 'Save changes',
            change: 'Change',
            chooseDoctor: 'Choose doctor',
            chooseDate: 'Choose date',
            chooseMedicalDate: 'Choose medical examination date',
            created: 'created',
            chooseTime: 'Choose time',
            createSuccess: 'Create the appointments of doctor successfully',
            noCreated: 'No appointment schedule created',
            cancel: 'Cancel'
        },
        specialtyInfor: {
            moreInfor: 'More specialty information',
            avatar: 'Avatar',
            chooseSpecialty: 'Choose specialty',
            introVi: 'Introductory information (Vietnamese)',
            introEn: 'Introductory information (English)',
            createSuccess: 'Create specialty information successfully',
            editSuccess: 'Edit specialty information successfully',
            save: 'Save changes',
            change: 'Change',
            cancel: 'Cancel'
        },
        hospitalInfor: {
            moreInfor: 'More hospital information',
            avatar: 'Avatar',
            chooseSpecialty: 'Choose specialty',
            introVi: 'Introductory information (Vietnamese)',
            introEn: 'Introductory information (English)',
            createSuccess: 'Create hospital information successfully',
            editSuccess: 'Edit hospital information successfully',
            save: 'Save changes',
            change: 'Change',
            cancel: 'Cancel'
        },
        handbookInfor: {
            moreInfor: 'Create Handbook',
            image: 'Post photo',
            createNew: 'Create a new handbook',
            editHandbook: 'Edit created handbook',
            chooseHandbook: 'Choose created handbooks',
            contentVi: 'Content (Vietnamese)',
            titleVi: 'Title (Vietnamese)',
            contentEn: 'Content (English)',
            titleEn: 'Title (English)',
            handbook: 'Handbook',
            createSuccess: 'Create a handbook successfully',
            editSuccess: 'Edit handbook successfully',
            change: 'Change',
            save: 'Save changes',
            create: 'Create',
            cancel: 'Cancel'
        }
    },
    detailDoctor: {
        schedule: 'Examination schedule',
        address: 'Examination address',
        price: 'Examination price',
        specialty: 'Specialty: ',
        description: 'Description: ',
        priority: 'Get priority treatment before booking through BookingCare',
        showDetail: 'See detail',
        hiddenDetail: 'Hide detailed price',
        paymentMethod: 'Patients can pay by : ',
        examinationBooking: 'Make an appointment',
        examinationDate: 'Examination day: ',
        examinationTime: 'Examination time',
        examinationReason: 'Reason for examination',
        book: 'Book',
        cancel: 'Cancel',
        bookingSucess: 'You have successfully booked the appointment',
        exceedBooking: 'You have overbooked the number of appointments (Maximum: 10)',
        dulicateBooking: 'The appointment at this time has been booked in advance'
    }
}